server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_LOCATION:file:D:\Project\Bank\config\local}
logging:
  level:
    root: WARN